<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
 {
    /* Fetching roles for a given user Id */
    public function getAllGenres(){
        $query = $this->getEntityManager()->createQuery("SELECT g FROM AppBundle:Genre g ORDER BY g.genre_name ASC");
        $genres = $query->getResult();
        if($genres){
            return $genres;
        } else{
            return null;
        }
    }

}
