<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllMovies(){
        $query = $this->getEntityManager()->createQuery("SELECT m FROM AppBundle:Movie m ORDER BY m.movie_name ASC");
        $movies = $query->getResult();
        if($movies){
            return $movies;
        } else{
            return null;
        }
    }
}
