<?php

namespace AppBundle\Repository;

/**
 * User_has_RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_has_RoleRepository extends \Doctrine\ORM\EntityRepository
 {
    /* Fetching roles for a given user Id */
    
    

    public static function getTheRoles($userId, EntityManager $em) {
        $repository = $em->getRepository("AppBundle:User_has_Role");
        //$result = $repository->findBy(["User_user_id" => $userId]);
        $result = $repository->findBy(["user" => $userId]);
        if ($result) {
            $userRoles = array();
            $i = 0;
            foreach ($result as $record) {
                $userRoles[$i] = Role::getTheRole($record->getRole(), $em);
                $i++;
            }
            return $userRoles;
        } else {
            return null;
        }
    }

}
