# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    em:
        class: Doctrine\ORM\EntityManager
    
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
